group = gg.pufferfish.pufferfish
version = 1.21.11-R0.1-SNAPSHOT

mcVersion = 1.21.11
apiVersion = 1.21.11

paperCommit = cc3dae7a39a38192688696619c276df569bb485f
updatingMinecraft = true

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false

