group = gg.pufferfish.pufferfish
version = 1.21.11-R0.1-SNAPSHOT

mcVersion = 1.21.11
apiVersion = 1.21.11

paperCommit = 997f5054574db24d114d25d7ed88b0c9db3573a0
updatingMinecraft = false

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false

