group = gg.pufferfish.pufferfish
version = 1.21.11-pre5-R0.1-SNAPSHOT

mcVersion = 1.21.11-pre5
apiVersion=1.21.11

paperCommit = ffce96cf3e9231b5efe1d93aa0df4e25ab309dd8
updatingMinecraft = true

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false

