name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v4
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Release Pufferfish
        if: "contains(github.event.commits[0].message, '[release]')"
        uses: softprops/action-gh-release@master
        with:
          name: "Pufferfish build ${{ env.BUILD_NUMBER }}"
          tag_name: "ver-1.21.6-b${{ env.BUILD_NUMBER }}"
          files: |
            pufferfish-server/build/libs/pufferfish-paperclip-1.21.6-R0.1-SNAPSHOT-mojmap.jar
            pufferfish-api/build/libs/pufferfish-api-1.21.6-R0.1-SNAPSHOT.jar
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_commitish: "${{ github.sha }}"
          draft: false
          prerelease: false
